spring:
  application:
    name: real-estate-backend
  datasource:
     url: jdbc:mysql://localhost:3306/real_estate_saas
     username: root
     password: password
     driver-class-name: com.mysql.cj.jdbc.Driver
