package com.example.realestatebackend;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@org.mybatis.spring.annotation.MapperScan("com.example.realestatebackend.mapper")
public class RealEstateBackendApplication {

    public static void main(String[] args) {
        SpringApplication.run(RealEstateBackendApplication.class, args);
    }

}
